In [2]:
import numpy as np
from collections import defaultdict

In [3]:
Q = defaultdict(lambda: np.zeros(env.action_space.n))

In [7]:
import gym

In [8]:
env = gym.make("CartPole-v0")

In [10]:
state = env.reset()

In [27]:
print(env.observation_space.low)
print(env.observation_space.high)

[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]
[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]


In [23]:
dir(env.observation_space)

['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'bounded_above',
 'bounded_below',
 'contains',
 'dtype',
 'from_jsonable',
 'high',
 'is_bounded',
 'low',
 'np_random',
 'sample',
 'seed',
 'shape',
 'to_jsonable']

In [28]:
import pandas as pd

In [34]:
pd.cut([-2.4, 2.4], bins=8, retbins=True)[1]

array([-2.4048, -1.8   , -1.2   , -0.6   ,  0.    ,  0.6   ,  1.2   ,
        1.8   ,  2.4   ])