In [2]:
import numpy as np
from collections import defaultdict

In [3]:
Q = defaultdict(lambda: np.zeros(env.action_space.n))

In [1]:
import gym

In [92]:
pong = gym.make("Pong-v0")
cart = gym.make("CartPole-v0")

In [93]:
pongt_state = pong.reset()
cart_state = cart.reset()

In [96]:
print(pong.observation_space.shape)
print(cart.observation_space.shape)

(210, 160, 3)
(4,)


In [97]:
print(pong.action_space.n)
print(cart.action_space.n)

6
2


In [87]:
#dir(env.action_space)

In [98]:
pong_state_size = pong.observation_space.shape
cart_state_size = cart.observation_space.shape

In [99]:
print(pong_state_size)
print(cart_state_size)

(210, 160, 3)
(4,)


In [100]:
#np.random.random((1, *pong_state_size))
#np.random.random((1, *cart_state_size))

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 ...

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]]


In [104]:
pong_state_size[:]

(210, 160, 3)